mutation CreateActivityType($data: ActivityTypeInput!) {
  createActivityType(data: $data) {
    category
    emissions
    id
    name
    unit
    vehicleAttributes {
      fuelType
      motoEngine
      vehicleDecade
      vehicleType
    }
  }
}