query GetPersonalVehicles($userId: Float) {
  getPersonalVehicles(userId: $userId) {
    id
    fuel_type
    moto_engine
    name
    vehicle_category
    vehicle_type
    year_of_construction
    user {
      id
    }
  }
}