query GetUserByNickname($nickname: String!) {
  getUserByNickname(nickname: $nickname) {
    id
    nickname
    firstName
    lastName
    avatarUrl
    posts {
      id
    }
    followers {
      id
      avatarUrl
    }
    following {
      id
      avatarUrl
    }
  }
}
