name: Test, compile and push client and server to production

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  test-client:
    uses: WildCodeSchool/2023-11-wns-bleu-g3/.github/workflows/tests-front.yml@dev

  e2e-tests:
    uses: WildCodeSchool/2023-11-wns-bleu-g3/.github/workflows/e2e.yml@dev

  integration-tests:
    uses: WildCodeSchool/2023-11-wns-bleu-g3/.github/workflows/integration-tests.yml@dev

  build-and-push-server:
    needs:
      - integration-tests
      - e2e-tests
    uses: WildCodeSchool/2023-11-wns-bleu-g3/.github/workflows/build-backend.yml@dev
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: greenfoot/greenfoot-back-dev

  build-and-push-client:
    needs:
      - test-client
      - e2e-tests
    uses: WildCodeSchool/2023-11-wns-bleu-g3/.github/workflows/build-frontend.yml@dev
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: greenfoot/greenfoot-front-dev

  notify-vps:
    needs:
      - build-and-push-client
      - build-and-push-server
    runs-on: ubuntu-latest
    steps:
      - name: Call VPS webhook to update dev
        uses: wei/curl@master
        with:
          args: https://dev.1123-bleu-3.wns.wilders.dev/hooks/update-dev
